### ISSUE TITLE
"No deposits" message text is way too big

### ISSUE THREAD

**Issue by renc-curvelabs** [PrimeDAO/prime-deals-dapp#748] opened 2022-04-22 19:54 UTC
On the funding page Deposits section:

![image.png](https://images.zenhubusercontent.com/609a98a27efca047604a4836/ad6dc986-4e90-4a51-a0d6-278652dca731)

**Comment by vipergtsrz** [comment] 2022-04-26 19:38
This is a duplicate of #774 which had code checked in to fix today

**Closed by vipergtsrz** 2022-04-26 19:38 UTC
